### ISSUE TITLE
Vehicle color classification

### ISSUE THREAD

**Issue by AqsaHassan** [Helias/Car-Model-Recognition#4]
Hey.. Can I use this project for vehicle color classification?? or can you give any idea related to vehicle color classification?? @Helias

**Comment by Helias** [comment]
Hey, I edited the title of this issue, put a better title next time :wink: 

I don't know, I think so, but probably is not oriented for that, so you will not get good results with this.
But you can try, why not, it could have a 70% of accuracy maybe.

Ideally, you should use vehicle-detection and after check the color inside the part detected of the vehicle, this could be easier and better.

There are several projects about vehicle detection like:
[Multinet](https://github.com/MarvinTeichmann/MultiNet)
[YOLO_ResNet](https://github.com/makatx/YOLO_ResNet)
[KittiBox](https://github.com/MarvinTeichmann/KittiBox)
[Vehicle-detection](https://github.com/tatsuyah/vehicle-detection/)

**Comment by AqsaHassan** [comment]
I gave a try to your suggested approach and it worked...Thank you!
