### ISSUE TITLE
files are not found

### ISSUE THREAD

**Issue by andreimihale** [Helias/Car-Model-Recognition#6]
Hi! I have the next problem. It does not read the files as it should

OS: Windows 8.1

**### This is the issue**

![console](https://user-images.githubusercontent.com/48432916/91664296-de42de00-eaf6-11ea-9a70-6dc5379a3cb4.PNG)

### **the folder structure is this**

![structure root](https://user-images.githubusercontent.com/48432916/91664311-05011480-eaf7-11ea-8509-835eb6e2dec1.PNG)

### **this is the dataset folder**

![dataset](https://user-images.githubusercontent.com/48432916/91664315-0b8f8c00-eaf7-11ea-910f-6cb54062e5ed.PNG)

### **this is the num_class var**

![num class](https://user-images.githubusercontent.com/48432916/91664332-2bbf4b00-eaf7-11ea-9820-f9562dc84357.PNG)

### **this is the test csv ( 668 lines ) **

![csv](https://user-images.githubusercontent.com/48432916/91664343-409bde80-eaf7-11ea-9b84-45aaf0136293.PNG)

### **this is the train csv ( 1324 lines )**

![train csv](https://user-images.githubusercontent.com/48432916/91664369-85c01080-eaf7-11ea-9c75-aa6fc246c1a0.PNG)

L.E. Everytime is a new image. So i don t have the same path error 2 times in a row. Even if i don t save manually classes in num_classes it still give me the same error

**Comment by Helias** [comment]
Are you using WSL as terminal?
Did you try to change the `path` from `\path\of\the\file` to `path/of/the/file` ?

**Comment by andreimihale** [comment]
> Are you using WSL as terminal?
> Did you try to change the `path` from `\path\of\the\file` to `path/of/the/file` ?

i solved if finally. It is an error on windows about how you manipulate path files. if you need i can create a windows repo after i finish and do a PR

**Comment by Helias** [comment]
if it is necessary for the compatibility of Windows, yes, why not ;-)
I will be gratefully, but it's important to do not break the software compatibility with other platform :wink:

**Comment by Shame-fight** [comment]
> > Are you using WSL as terminal?
> > Did you try to change the `path` from `\path\of\the\file` to `path/of/the/file` ?
> 
> i solved if finally. It is an error on windows about how you manipulate path files. if you need i can create a windows repo after i finish and do a PR

I have the same question,what should I do to solving it? I also use win8

**Comment by Helias** [comment]
it's an issue related to PATH, try to use `this/style/of/path` and if it does not work use `this\style\` with backslash
