### ISSUE TITLE
error when run 'python main.py -t'

### ISSUE THREAD

**Issue by Shame-fight** [Helias/Car-Model-Recognition#8]
Thanks for your work, when I run `python  main.py -t` for training, I ran into a problem:
This seems to be a multithreading problem, I don't know how to solve it, can you help me?
looking forward to your  replay.
@Helias 
![1](https://user-images.githubusercontent.com/30313218/117599566-a0658180-b17c-11eb-9090-12a566cfd79e.jpg)

**Comment by Shame-fight** [comment]
I have solved this problem just adding codes
 `if __name__ == '__main__':` before traing code.

**Comment by Helias** [comment]
thank you to share the solution 👍
